version: "3.2"

services:

  angular:
    container_name: angular
    build: .
    ports:
      # externalport : internalport
      - "4200:4200"
    environment:
      - NODE_ENV=production
      - ALLOW_ORIGIN=angular
      # Settings to connect to our local mongo instance 
      - DB_USER=mongouser
      - DB_PASSWORD=secret
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_DATABASE=imagexample
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - frontend
    privileged: true
      
  mongo:
    image: mongo:latest
    # container_name: mongo
    volumes:
      - db-data:/data/mongodb/db
    ports:
      - "27017:27017"
    environment:
      # - MONGO_DB_USER=${MONGO_DB_USER}
      # - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=imagexample
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadminpassword
    networks:
      - frontend
    command: mongod --auth --storageEngine wiredTiger # --quiet

networks:
  frontend:

volumes:
  db-data:
